#! /bin/zsh

autoload colors && colors

function title {
    if [[ $TERM == screen* ]]; then
        # Use these two for GNU Screen:
        print -nR $'\ek'$1$'\e'"\\"
        shift
#       print -nR $'\e]0;'$*$'\a'
        print -nR $'\e_screen \005 | '$*$'\e'"\\"
    elif [[ $TERM == "xterm" || $TERM == rxvt* ]]; then
        # Use this one instead for XTerms:
        shift
        print -nR $'\e]0;'$@$'\a'
    fi
}

precmd() {
    local git_dir ref termtitle

    termtitle=$(print -P "%n@%m:%~ | ${COLUMNS}x${LINES} | %y")
    title zsh "$termtitle"

    psvar=()
    git_dir=$(git-rev-parse --git-dir 2> /dev/null) || return
    ref=$(git-symbolic-ref HEAD 2> /dev/null) || return
    psvar[1]=${$(readlink -f ${git_dir:h})/$HOME/'~'}
    psvar[2]=${ref#refs/heads/}
}

_mad_prompt_setup() {
    local rst
    local -a pcc

    rst="%{$reset_color%}"
    pcc[1]="%{$reset_color${1:-$fg_no_bold[green]}%}"
    pcc[2]="%{$reset_color${2:-$fg_no_bold[yellow]}%}"
    pcc[3]="%{$reset_color${3:-$fg_no_bold[cyan]}%}"

#%{$'\e[s\e[A\e[4Dblah\e[u'$reset_color%}
#%{$'\e[400C\e[20D'%}"────────────────────
    PROMPT="\
$pcc[1]┌─(%B%T$pcc[1])──%(1v.<$pcc[3]%1v %B%U%2v%u$pcc[1]>.)──
$pcc[1]└[$pcc[2]%{%(?..%S)%}%m%s$pcc[1]] $rst"
    RPROMPT="$pcc[1](%B%~$pcc[1])$rst"
    POSTEDIT=$reset_color
}

if [ $UID -eq 0 ]; then
    PATH=~root/bin:/usr/local/sbin:/usr/sbin:/sbin:$PATH
    PROMPT="%{$reset_color$fg_bold[yellow]%}[%{$fg_bold[red]%}%n %m%{$fg_bold[yellow]%}]%{$reset_color%} "
    RPROMPT="%{$reset_color$fg_no_bold[red]%}(%{$fg_bold[red]%}%~%{$fg_no_bold[red]%})%{$reset_color%} "
else
    PATH="/usr/lib/ccache:${HOME}/bin:${HOME}/.madconf/bin:${PATH}"
    _mad_prompt_setup
fi

case "$TERM" in
    screen)
        PROMPT="${PROMPT}%{kzsh\\%}"

        preexec () {
            local CMD=${1[(wr)^(*=*|sudo|exec|-*)]}
            echo -ne "\ek$CMD\e\\"
        }
    ;;
    xterm|rxvt-unicode)
        PROMPT="${PROMPT}%{]2;zsh%}"

        preexec () {
            local CMD=${1[(wr)^(*=*|sudo|exec|-*)]}
            echo -ne "\e]2;$CMD\007"
        }
    ;;
    *);;
esac
