#!/bin/sh
#
# func/vcsh
#
# set the context for vcs-home operations
#
# Copyright © 1994–2008 martin f. krafft <madduck@madduck.net>
# Released under the terms of the Artistic Licence 2.0
#
# Source repository: http://git.madduck.net/v/etc/zsh.git
#

local  FGIT_BASE="$HOME/src/dotfiles"

if [ "${1:---help}" = '--help' ] || [ $# -gt 1 ]; then
  echo "usage: ${0##*/} reponame" >&2
  echo "usage: ${0##*/} -l" >&2
  [ "$1" = '--help' ]
  return $?

elif [ "$1" = '-l' ]; then
  for i in $FGIT_BASE/*.git; do
    i="${i#$FGIT_BASE/}"
    echo "${i%.git}"
  done
  echo none
  return 0
fi

if [ "$1" = "none" ]; then
  unset GIT_DIR GIT_WORK_TREE
  return 0
else
  if [ ! -d "$FGIT_BASE/${1}.git" ]; then
    echo E: no repository found for "$1" >&2
    return 2
  fi
fi

export GIT_DIR="$FGIT_BASE/${1}.git"

typeset -g GIT_WORK_TREE=$(git config --get core.worktree)
if [[ $GIT_WORK_TREE == /* ]]; then
  export GIT_WORK_TREE
else
  export GIT_WORK_TREE="$GIT_DIR/$GIT_WORK_TREE"
fi

git status

PS1="%S{${0##*/}:$1}%s$PS1" $SHELL -i
